### ISSUE TITLE
For Consideration: Rule to replace U+135E U+135F with U+135D

### ISSUE THREAD

**Issue by dyacob** [silnrsi/font-abyssinica#2]
Though it should be a rare occurrence, should U+135F immediately follow U+135F (or vice-versa) in text, the two symbols should be replaced with U+135D.  This is indeed what U+135D is intended for and the user should generally be doing this manually.  The following OpenType rule should be able to do the same automatically:

```
lookup VOWEL_GEM {
  sub [uni135E uni135F] [uni135E uni135F] by uni135D;
} VOWEL_GEM;

feature calt {
  lookup VOWEL_GEM;
} calt;
```

**Comment by LornaSIL** [comment]
If it had a decomposition, then it would possibly make sense. Most combining marks don't have decompositions. I believe this is partially because they would be difficult to implement and know how to implement...whether stacked or side-by-side, etc.
For example, this Greek character seems to have a decomposition (00A8 0301):
```
0385;GREEK DIALYTIKA TONOS;Sk;0;ON;00A8 0301;;;;N;GREEK SPACING DIAERESIS TONOS;;;;
```
And if I were implementing Greek I would consider writing the sort of rule you are suggesting.

However, these characters do not have decompositions and I would not expect the font to do anything smart except to attach to the base character.
```
0310;COMBINING CANDRABINDU;Mn;230;NSM;;;;;N;NON-SPACING CANDRABINDU;;;;
0352;COMBINING FERMATA;Mn;230;NSM;;;;;N;;;;;
0356;COMBINING RIGHT ARROWHEAD AND UP ARROWHEAD BELOW;Mn;220;NSM;;;;;N;;;;;
135D;ETHIOPIC COMBINING GEMINATION AND VOWEL LENGTH MARK;Mn;230;NSM;;;;;N;;;;;
135E;ETHIOPIC COMBINING VOWEL LENGTH MARK;Mn;230;NSM;;;;;N;;;;;
135F;ETHIOPIC COMBINING GEMINATION MARK;Mn;230;NSM;;;;;N;;;;;
```
